title: 4bitcss
description: >- # this means to ignore newlines until "baseurl:"
  4bitcss: CSS3 16-color schemes.
permalink: pretty
analyticsID: G-27ME7M0HYR
defaults:
  - values:
      layout: "default"
    
